product_get:
    path: /api/product/{id}
    controller: App\Controller\ProductController::getById
    methods: GET

product_get_all:
    path: /api/product
    controller: App\Controller\ProductController::getAll
    methods: GET

product_create:
    path: /api/product
    methods: POST
    controller: App\Controller\ProductController::create

product_delete:
    path: /api/product/{id}
    methods: DELETE
    controller: App\Controller\ProductController::delete

product_option_get:
    path: /api/product_option/{id}
    controller: App\Controller\ProductOptionController::getById
    methods: GET

product_option_create:
    path: /api/product_option
    methods: POST
    controller: App\Controller\ProductOptionController::create


controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


